---
- name: Ensure Operating System Requirements
  fail:
    msg: "The {{inventory_hostname}} host with operating system {{ansible_distribution}} did not meet the required operating systems: {{SUPPORTED_DISTROS}}"
  when: >
    ansible_distribution not in SUPPORTED_DISTROS
- name: Install virt packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ VIRT_PACKAGES }}"
- name: Download the Centos 8 Stream ISO.
  get_url:
    url: "{{ APP_DOWNLOAD_URL }}"
    dest: "{{ APP_DOWNLOAD_PATH }}"
- name: Check if freeipa.qcow2 exists
  stat:
    path: /var/lib/libvirt/images/freeipa.qcow2
  register: qcow2_exists
- name: Create freeipa.qcow2
  command: qemu-img create -f qcow2 /var/lib/libvirt/images/freeipa.qcow2 {{ VM_DISK_SIZE }}
  become: yes
  when: qcow2_exists.stat.exists == false
- name: Check if freeipa virtual machine exists.
  virt:
    name: freeipa
    command: get_xml
    uri: qemu:///system
  register: vm_exists
  ignore_errors: true
  become: yes
- name: Install the freeipa virtual machine.
  command: virt-install --location {{ APP_DOWNLOAD_PATH }} -n freeipa --memory=4000 --vcpus=2 --cpu mode=host-model --machine=pc --disk path=/var/lib/libvirt/images/freeipa.qcow2,device=disk,bus=virtio --features eoi=on,hap=on --rng=random,rate_bytes=6000,rate_period=300 --channel unix,target_type=virtio,name=org.qemu.guest_agent.0 --video qxl --memballoon virtio --accelerate --network bridge={{NETWORK_BRIDGE_CONNECTION}},mac={{ VM_MAC_ADDRESS }} --initrd-inject {{ KICKSTART_PATH }} -x "ks=file:/anaconda-ks.cfg"
  become: yes
  when: vm_exists is failed


